### ISSUE TITLE
"search" is absent on page

### ISSUE THREAD

**Issue by eikeco** [froots/design-testing#16]
Hi @froots 

I get the following when running a test on the search component.
<img width="779" alt="galen" src="https://cloud.githubusercontent.com/assets/1248419/20450496/fc44deca-ade8-11e6-8fa5-a0ccc25b876f.png">

The element with class "search" is there!

macOS 10.12 
Node: v6.9.1
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Any ideas?

**Comment by froots** [comment]
If you have run `npm run serve` to start the webserver, this serves the contents of the `dist` directory. So `dist` shouldn't be part of the URL. So the command should read:

`galen check test/visual/specs/search.gspec --url "http://localhost:8000/styleguide/search.html" --size "540x960" --htmlreport "test/visual/report"`

Was that command taken from the book? If so I'll make a correction.

Let me know if that did the trick as it did for me.

**Comment by froots** [comment]
@eikeco closing this. Feel free to re-open if you still have a problem. :-)
